sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  npm i -g npm@^5.3.0
script:
  - npm start validate
after_success:
  - npx codecov
  - npx semantic-release pre && npm publish && npx semantic-release post
branches:
  only:
    - master
